#!/usr/bin/env python3
"""Compose docs/social-preview.png from docs/bg-raw.png (generated by media-tools).

Layout: 1280x640 cover-crop of the background + left-to-right dark gradient
overlay + title / subtitle text. Run from the repo root:

    python3 scripts/make-banner.py
"""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
W, H = 1280, 640
FONT_BOLD = "/System/Library/Fonts/Supplemental/Arial Bold.ttf"
FONT_REG = "/System/Library/Fonts/Supplemental/Arial.ttf"
FONT_CJK = "/System/Library/Fonts/Supplemental/Arial Unicode.ttf"
ACCENT = (77, 107, 254)  # DSH blue #4D6BFE


def cover_crop(img: Image.Image, w: int, h: int) -> Image.Image:
    scale = max(w / img.width, h / img.height)
    img = img.resize((round(img.width * scale), round(img.height * scale)))
    left = (img.width - w) // 2
    top = (img.height - h) // 2
    return img.crop((left, top, left + w, top + h))


def main() -> None:
    bg = Image.open(ROOT / "docs/bg-raw.png").convert("RGBA")
    canvas = cover_crop(bg, W, H)

    # Left-to-right dark gradient so text stays legible.
    alpha = Image.linear_gradient("L").resize((W, H)).point(
        lambda v: 235 - int((235 - 40) * v / 255)
    )
    overlay = Image.new("RGBA", (W, H), (10, 16, 44, 255))
    overlay.putalpha(alpha)
    canvas = Image.alpha_composite(canvas, overlay)

    draw = ImageDraw.Draw(canvas)
    title_font = ImageFont.truetype(FONT_BOLD, 56)
    en_font = ImageFont.truetype(FONT_REG, 27)
    cjk_font = ImageFont.truetype(FONT_CJK, 23)
    tag_font = ImageFont.truetype(FONT_CJK, 17)

    x = 62
    # Accent bar + title
    draw.rectangle((x, 236, x + 8, 300), fill=ACCENT)
    draw.text((x + 26, 226), "dsh-media-skills", font=title_font, fill=(255, 255, 255))
    draw.text((x + 26, 300), "Free image reading & generation for DeepSeek Harness",
              font=en_font, fill=(215, 224, 255))
    draw.text((x + 26, 342), "读图 · 生图 —— 为 DeepSeek Harness 而生的免费 Skill",
              font=cjk_font, fill=(159, 176, 224))

    # Small pill tag bottom-left
    tag = "DeepSeek Harness  ·  dsh-plugin"
    draw.rounded_rectangle((x + 26, 540, x + 26 + 330, 576), radius=18, outline=ACCENT, width=2)
    draw.text((x + 44, 548), tag, font=tag_font, fill=(215, 224, 255))

    out = ROOT / "docs/social-preview.png"
    canvas.convert("RGB").save(out)
    print("wrote:", out, f"({W}x{H})")


if __name__ == "__main__":
    main()
